export const API_PATHS = {
  auth: {
    register: '/api/v1/auth/register',
    login: '/api/v1/auth/login',
    refresh: '/api/v1/auth/refresh',
    logout: '/api/v1/auth/logout',
    me: '/api/v1/auth/me',
  },
  users: {
    detail: (username: string) => `/api/v1/users/${username}`,
    repositories: (username: string) => `/api/v1/users/${username}/repositories`,
    contributions: (username: string) => `/api/v1/users/${username}/contributions`,
    pullRequests: (username: string) => `/api/v1/users/${username}/pull-requests`,
    contributorStats: (username: string) => `/api/v1/users/${username}/stats/contributor`,
    authorStats: (username: string) => `/api/v1/users/${username}/stats/author`,
    badges: (username: string) => `/api/v1/users/${username}/badges`,
  },
  repositories: {
    list: '/api/v1/repositories',
    create: '/api/v1/repositories',
    detail: (repositoryId: string) => `/api/v1/repositories/${repositoryId}`,
    contributors: (repositoryId: string) => `/api/v1/repositories/${repositoryId}/contributors`,
    merges: (repositoryId: string) => `/api/v1/repositories/${repositoryId}/merges`,
    pullRequests: (repositoryId: string) => `/api/v1/repositories/${repositoryId}/pull-requests`,
    stats: (repositoryId: string) => `/api/v1/repositories/${repositoryId}/stats`,
    dashboard: (repositoryId: string) => `/api/v1/repositories/${repositoryId}/dashboard`,
  },
  pullRequests: {
    list: '/api/v1/pull-requests',
    detail: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}`,
    createDraft: (repositoryId: string) => `/api/v1/repositories/${repositoryId}/pull-requests/draft`,
    draft: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/draft`,
    aiAnalyze: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/ai-analyze`,
    aiAnalysis: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/ai-analysis`,
    submit: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/submit`,
    contributorComment: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/contributor-comment`,
    accept: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/accept`,
    requestChanges: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/request-changes`,
    reject: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/reject`,
    merge: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/merge`,
    gradeOverride: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/grade-override`,
    rejectReason: (pullRequestId: string) => `/api/v1/pull-requests/${pullRequestId}/reject-reason`,
  },
  search: {
    global: '/api/v1/search',
  },
  notifications: {
    list: '/api/v1/notifications',
    unreadCount: '/api/v1/notifications/unread-count',
    read: (notificationId: string) => `/api/v1/notifications/${notificationId}/read`,
    readAll: '/api/v1/notifications/read-all',
  },
  tags: {
    list: '/api/v1/tags',
    popular: '/api/v1/tags/popular',
  },
  merges: {
    detail: (mergeId: string) => `/api/v1/merges/${mergeId}`,
  },
} as const;
